name: HA and HACS Validate

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ha_and_hacs_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Hassfest validation
        continue-on-error: true
        uses: home-assistant/actions/hassfest@master
      - name: HACS validation
        continue-on-error: true
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands
